name: Python Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  install-pip-deps:
    name: Install
    runs-on: self-hosted

    steps:
      - name: Deploy to Dev
        run: echo "Installing pip libraries.."
        
      - name: Checkout code using v3.5.2
        uses: actions/checkout@v3.5.2
      
      - name: Clone python-greetings repository
        uses: actions/checkout@v3.5.2
        with:
          repository: 'mtararujs/python-greetings'
          path: 'python-greetings'
      
      - name: Install dependencies
        run: |
          cd python-greetings
          pip install -r requirements.txt


  deploy-to-dev:
    name: Deploy
    runs-on: self-hosted
    needs: [install-pip-deps]

    steps:

      - name: Checkout code using v3.5.2
        uses: actions/checkout@v3.5.2
      
      - name: Deploy to Dev
        run: echo "Deploying to Dev environment.."


  tests-on-dev:
    name: Tests dev
    runs-on: self-hosted
    needs: [deploy-to-dev]

    steps:
      
      - name: Run tests on Dev
        run: echo "Running tests on Dev environment.."


  deploy-to-staging:
    name: Deploy stg
    runs-on: self-hosted
    needs: [tests-on-dev]

    steps:
      
      - name: Deploy to Staging
        run: echo "Deploying to Staging environment.."


  tests-on-staging:
    name: Tests stg
    runs-on: self-hosted
    needs: [deploy-to-staging]

    steps:
      
      - name: Run tests on Staging
        run: echo "Running tests on Staging environment.."


  deploy-to-preprod:
    name: Deploy preprod
    runs-on: self-hosted
    needs: [tests-on-staging]

    steps:
      
      - name: Deploy to Preprod
        run: echo "Deploying to Preprod environment.."


  tests-on-preprod:
    name: Tests preprod
    runs-on: self-hosted
    needs: [deploy-to-preprod]

    steps:
      
      - name: Run tests on Preprod
        run: echo "Running tests on Preprod environment.."


  deploy-to-prod:
    name: Deploy prod
    runs-on: self-hosted
    needs: [tests-on-preprod]

    steps:
      
      - name: Deploy to Prod
        run: echo "Deploying to Prod environment.."


  tests-on-prod:
    name: Tests prod
    runs-on: self-hosted
    needs: [deploy-to-prod]

    steps:
      
      - name: Run tests on Prod
        run: echo "Running tests on Prod environment.."
