name: Python Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

    workflow_dispatch:

jobs:
  install-pip-deps:
    runs-on: ubuntu-latest

    steps:
      
      - name: Set up Python
        run: echo "Installing all required dependencies.."


  deploy-to-dev:
    runs-on: ubuntu-latest

    steps:
      
      - name: Deploy to Dev
        run: echo "Deploying to Dev environment.."


  tests-on-dev:
    runs-on: ubuntu-latest

    steps:
      
      - name: Run tests on Dev
        run: echo "Running tests on Dev environment.."


  deploy-to-staging:
    runs-on: ubuntu-latest

    steps:
      
      - name: Deploy to Staging
        run: echo "Deploying to Staging environment.."


  tests-on-staging:
    runs-on: ubuntu-latest

    steps:
      
      - name: Run tests on Staging
        run: echo "Running tests on Staging environment.."


  deploy-to-preprod:
    runs-on: ubuntu-latest

    steps:
      
      - name: Deploy to Preprod
        run: echo "Deploying to Preprod environment.."


  tests-on-preprod:
    runs-on: ubuntu-latest

    steps:
      
      - name: Run tests on Preprod
        run: echo "Running tests on Preprod environment.."


  deploy-to-prod:
    runs-on: ubuntu-latest

    steps:
      
      - name: Deploy to Prod
        run: echo "Deploying to Prod environment.."


  tests-on-prod:
    runs-on: ubuntu-latest

    steps:
      
      - name: Run tests on Prod
        run: echo "Running tests on Prod environment.."
